### ISSUE TITLE
Communication with physical devices from Conbee/Deconz not working

### ISSUE THREAD

**Issue by a94marbo** [home-assistant/operating-system#1063]
**Hardware Environment**

- [ ] Raspberry Pi [4] B 2MB

**Home Assistant OS release:**
- [ ] Fresh installation of release 5.6

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

ZigBee devices under Deconz (latest verion) with a ConBee stick (latest FW) is shown in interface, and seem to work. Turning lights on and off changes the states in HA, but no communication wirh physical device is done a the light remains in the state it was, even if the state in HA is changed. Not possible to add devices either.
Devices work in HA 4.x branch. Fault not visable at all.

**Comment by agners** [comment]
This sounds more like a deCONZ Add-On issue. When you tested with HAOS 4.x branch, di you use the same Add-On version? Can you try downgrading and see if that makes it work again on the same setup otherwise (using `ha os update --version 4.19`).

**Comment by a94marbo** [comment]
I am using the same snapshot in both releases, i am restoring the same snapshot in 5.6 and 4.16. Zigbee do not work in 5.6

**Comment by agners** [comment]
I cannot reproduce this here:
```
# ha os info                                                                                                                                                                                                                                                                                                                  
board: rpi4-64                                                                                                                                                                                                                                                                                                                
boot: B                                                                                                                                                                                                                                                                                                                       
update_available: false                                                                                                                                                                                                                                                                                                       
version: "5.6"                                                                                                                                                                                                                                                                                                                
version_latest: "4.19"      
```

```
# ha supervisor info
addons:
...
- description: Control a Zigbee network with ConBee or RaspBee by Dresden Elektronik                                                                                                                                                                                                                                          
  icon: true                                                                                                                                                                                                                                                                                                                  
  logo: true                                                                                                                                                                                                                                                                                                                  
  name: deCONZ                                                                                                                                                                                                                                                                                                                
  repository: core                                                                                                                                                                                                                                                                                                            
  slug: core_deconz                                                                                                                                                                                                                                                                                                           
  state: started                                                                                                                                                                                                                                                                                                              
  update_available: false                                                                                                                                                                                                                                                                                                     
  version: 6.5.0                                                                                                                                                                                                                                                                                                              
  version_latest: 6.5.0   
```

I can control the lights from Home Assistant as well as using a remote (the state updates in HA).

Can you check the Add-On log as well as the Home Assistant Core log.

What are you using as `device:` in the Add-On configuration?
