### ISSUE TITLE
homeassistant crashing every day since an update in december

### ISSUE THREAD

**Issue by TrommlerHH** [home-assistant/operating-system#1232]
Hi,

also my raspberry pi with hass.io is crashing every days since december.

I already read a lot and posted in #1119 but I was advised to open a new post to get help.

I already reinstalled hass.io from the scratch and for almost two days it looked fine, but then it crashed again.

Any idea, what I could do?

This is my system:
## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4964
Installed Version | 1.10.1
Stage | running
Available Repositories | 747
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 21. Februar 2021, 1:00
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.11
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.9
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 4.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.0), File editor (5.2.0), Example (4.0.4), Google Assistant SDK (2.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

**Comment by Wesley-Vos** [comment]
Hi all,

I'm experiencing the same kind of problems on a Raspberry Pi 3 USB booting setup. Running latest updates of core, supervisor and OS.

The system becomes unresponsive after 2 to 24 hours after boot. Strangely, the HomeKit integration is still able to execute actions, however I can't access the UI. When it is frozen, I'm still able to ping the Pi but SSH is connecting really slow, but I don't get an error that the connection is refused, it just takes a long time to connect.   

There does not seem to be a clear reason for the freeze, no extreme high RAM usage or something similar. It even happens when I'm not actively 'working' on the system, when it's just performing some background tasks.

I hope that the reason can be revealed. I'm more than happy to share any diagnostics and/or logs if that can help!

**Comment by szurr** [comment]
Hi i have similar problem  system seems to working but was unavailable. I found that it was problem no my router side. If i rebooted router everything was back to normal. Now i changed router and it still occurs but like twice a year.
Check your router first 👍🏼

**Comment by agners** [comment]
Hard to tell where this exactly origins. There are definitly installations which do work stable on Raspberry Pi with Release 5, so I don't think there is a general problem.

One of the more likely causes is out-of-memory situations. Make sure to monitor memory usage e.g. using the [system monitor integration](https://www.home-assistant.io/integrations/systemmonitor/).

**Comment by denperss** [comment]
i do have the same issue, it overheads was working fine before... 
Now i have to turn it of and reboot..

**Comment by olirav** [comment]
I am having a similar issue, once or twice a day it the RPI3 will stop responding on both the standard and observer port, and the SSH will hang on the connecting stage. The issue usually resolves itself if left for half an hour or so.

When it recovers home-assistant.log only shows data from after the recovery - so no help there.

Plugging a monitor into the Pi when its froozen shows the below kernel messages that look to happen around the same time:

INFO: task kworker/0:0:30340 blocked for more than 122 seconds
Tainted: G   C  5.4.83-v7 #1
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message
INFO: task kworker/0:0:30340 blocked for more than 245 seconds
Tainted: G   C  5.4.83-v7 #1
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message
.............. Repeated untill ....................
Out of memory: Killed process 3762 (python3) total-vm:1020288kB, anon-rss629156kB, file-rss0kB, shmem-rss:0kB, UID:0 pgtables1016:kB oom_score_adj:0
systemd[1]: systemd-resolved.service: Watchdog timeout (limit 3min)!
systemd-coredump[32727]: Failed to get COMM: No such process

I am having a look at setting up the system monitor integration to check if this is a memory issue, but I suspect not

**Comment by TrommlerHH** [comment]
> Hard to tell where this exactly origins. There are definitly installations which do work stable on Raspberry Pi with Release 5, so I don't think there is a general problem.
> 
> One of the more likely causes is out-of-memory situations. Make sure to monitor memory usage e.g. using the [system monitor integration](https://www.home-assistant.io/integrations/systemmonitor/).

After two days without crashes (no idea why) it crashed again last night.

I added the recommended system monitor before, but I have no idea what to do with that, to be honest.

  # Example configuration.yaml entry
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free

Additionally my logs are claiming this:
"2021-02-21 11:24:58 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 50 and 64"

I already configured sensor for the cpu-temperatur. Can I just rename it?

**Comment by bschatzow** [comment]
@olirav > When it recovers home-assistant.log only shows data from after the recovery - so no help there.
You need to setup SSH on port 22222 or use a monitor and keyboard to see previous logs.  Lots of directions on how to do this. If you get stuck, send me a message and I will try and help you.

**Comment by olirav** [comment]
@bschatzow Thanks for the tip, I have set up the developer SSH access (Hadn't come across that before, much more useful level of access for fault finding)

Checking the docker logs ($ docker logs homeassistant) shows one of my automations cointaining a loop, doing far more iterations than I would expect (Lots of log entries), I think it was somehow missing its until clause - I have reworked it for the time being to have a fixed number of iterations, which should eliminate that.

If that wasn't the issue, then it will likely crop up again in the next couple of days - I will keep an eye on it.

I have set up the system monitor with the setup below, which should let me see from the logs if it is running out of memory/swap or overheating the CPU. Maybe this will be of use for someone else.

-- configuration.yaml ---
```
sensor:
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: memory_use
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: processor_use
      - type: processor_temperature
```

--- Sample Lovelace page to view logs --- 
```
  - title: System Monitor
    path: system-monitor
    badges: []
    cards:
      - type: sensor
        entity: sensor.memory_use
        graph: line
        hours_to_show: 12
        detail: 2
      - type: entities
        entities:
          - entity: sensor.memory_use
          - entity: sensor.memory_free
          - entity: sensor.load_1m
          - entity: sensor.swap_free
          - entity: sensor.swap_use
          - entity: sensor.processor_temperature
      - type: sensor
        entity: sensor.load_1m
        graph: line
        hours_to_show: 12
        detail: 2
```
