### ISSUE TITLE
Current measurement for RPi PoE+ hat not working

### ISSUE THREAD

**Issue by georgeboot** [home-assistant/operating-system#1450]
**Hardware Environment**

- [x] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [x] Fresh installation of release 6.1
- [ ] Updated from version x.y

**Problem**
I can't measure the power the PoE+ hat provides through the OS.

It's supposed to be measured using ([source](https://www.jeffgeerling.com/blog/2021/review-raspberry-pis-poe-hat-june-2021)):

```
cat /sys/devices/platform/rpi-poe-power-supply@0/power_supply/rpi-poe/current_now
```

Perhaps there are some modules that need to be enabled in the kernel to support the new hat out of the box?

**Comment by agners** [comment]
It seems that the PoE+ Hat support has been added with Raspberry Pi Kernel `1.20210527-1`. I'll update with the next release.

**Comment by agners** [comment]
Release 6.2 is out, please test and reopen in case this is still a problem.

**Comment by georgeboot** [comment]
@agners this still doesn't work on the latest version:

```
Logger: homeassistant.components.command_line
Source: components/command_line/__init__.py:48 
Integration: command_line (documentation, issues) 
First occurred: 15:55:35 (331 occurrences) 
Last logged: 21:25:34

Command failed (with return code 1): cat /sys/devices/platform/rpi-poe-power-supply@0/power_supply/rpi-poe/current_now
```

```yml
sensor:
- platform: command_line
  name: RPi CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(1) }}"
```
