### ISSUE TITLE
Unable to update HA Core and addons

### ISSUE THREAD

**Issue by Santanachia** [home-assistant/operating-system#2052]
### Describe the issue you are experiencing

after upgrading to 8.4, the system began to run very slowly despite the fact that only 5% of the processor and 60% of the memory is used. On top of that I am not able to update either HA Core or addons (the installation process takes hours and nothing changes).
![image](https://user-images.githubusercontent.com/4628507/183873520-2c25570b-ddee-4fc6-8c8f-f6f5e5104bbf.png)

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

8.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. upgrade from previous version

### Anything in the Supervisor logs that might be useful for us?

```txt
ERROR (MainThread) [supervisor.utils] Can't execute run while a task is in progress
```

### Anything in the Host logs that might be useful for us?

```txt
nothing suspicious
```

### Additional information

I can't do a downgrade, the system runs so slow that ssh constantly disconnects.

**Comment by Santanachia** [comment]
p.s.
When trying to install another addon:
```
Can't install homeassistant/aarch64-addon-ssh:9.6.0: 500 Server Error for http+docker://localhost/v1.41/auth: Internal Server Error ("Get "https://registry-1.docker.io/v2/": Get "https://auth.docker.io/token?account=vexator&client_id=docker&offline_token=true&service=registry.docker.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)")
```

**Comment by Santanachia** [comment]
update via ssh (port 22222) failed
```bash
Welcome to Home Assistant OS.

Use `ha` to access the Home Assistant CLI.
# ha os info
board: rpi3-64
boot: B
data_disk: .
update_available: false
version: "8.4"
version_latest: "8.4"
# ha os update --version=8.3
Error: Can't fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/8.3/haos_rpi3-64-8.3.raucb: Response payload is not completed
#
```

**Comment by Santanachia** [comment]
is it possible to download the file manually and update from local file?

**Comment by agners** [comment]
This sounds like internet connectivity issues. Can you ping github.com?

What is `ha network info` showing?

**Comment by Santanachia** [comment]
```
# ping github.com
github.com is alive!

# ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: true
interfaces:
- connected: false
  enabled: false
  interface: eth0
  ipv4:
    address: []
    gateway: null
    method: disabled
    nameservers: []
  ipv6:
    address: []
    gateway: null
    method: disabled
    nameservers: []
  primary: false
  type: ethernet
  vlan: null
  wifi: null
- connected: true
  enabled: true
  interface: wlan0
  ipv4:
    address:
    - 192.168.8.100/24
    gateway: 192.168.8.1
    method: auto
    nameservers:
    - 192.168.8.1
  ipv6:
    address:
    - fd14:a32f:31a8:3f00:7976:7a2e:b232:ae34/64
    - fe80::d1a9:8e60:7e7d:64b5/64
    gateway: fe80::16a3:2fff:fe31:a83f
    method: auto
    nameservers:
    - fe80::16a3:2fff:fe31:a83f
  primary: true
  type: wireless
  vlan: null
  wifi:
    auth: wpa-psk
    mode: infrastructure
    signal: 54
    ssid: Vex 2.4
supervisor_internet: true
```
