### ISSUE TITLE
IPv6 internet connectivity issues

### ISSUE THREAD

**Issue by darkxst** [home-assistant/operating-system#2549]
### Describe the issue you are experiencing

I am having issues with IPv6 internet connectivity from within HA. DNS and ipv6 across local LAN is working as expected. There is no internet connectivity via IPv6.

I am running this instance in a VM using bridged networking. HA ipv6 is configured to auto. Also tested on a clean install of HA 9.5 which also has the same issue.

I have tested ipv6 on my network using Ubuntu, Windows 11 and variety of debian/ubuntu based VM's and all of those work perfectly. So suspect this is an issue with the config in HA or perhaps just some default settings in Alpine linux are different.

I have noticed it affecting the following
* Import of blueprints from github
* Startup of Matter add-on failing to download certificates from github
However updates etc are working fine

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

On boot there is no ipv6 connectivity
```
# ping -6 google.com
No response from google.com
```
If I do an outbound ping from HA to the router, ipv6 starts working for some period of time (if I come back sometime later it will have stopped working again.)
```
# ping -6 fritz.box
fritz.box is alive!
# ping -6 google.com
google.com is alive!
```

### Anything in the Supervisor logs that might be useful for us?

```txt
None, downloads fail with Timeout
```

### Anything in the Host logs that might be useful for us?

```txt
None
```

## System Information

version | core-2023.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | beta
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 30.8 GB
disk_used | 20.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Terminal & SSH (9.7.0), Studio Code Server (5.5.7), ESPHome (2023.4.4), Mosquitto broker (6.2.1), Silicon Labs Multiprotocol (1.1.2), Matter Server (4.3.1), Cloudflared (4.1.5), Zigbee2MQTT (1.30.4-1), ESPHome (beta) (2023.5.0b3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 5, 2023 at 11:05 PM
-- | --
current_recorder_run | May 16, 2023 at 4:19 PM
estimated_db_size | 220.26 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Additional information

```
# ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: true
interfaces:
- connected: true
  enabled: true
  interface: enp2s1
  ipv4:
    address:
    - 192.168.178.52/24
    gateway: 192.168.178.1
    method: auto
    nameservers:
    - 192.168.178.1
    ready: true
  ipv6:
    address:
    - 2001:aab8:4166:ad01:6f7d:1fdb:1638:350f/64
    - fd86:92e7:d139:961b:115f:8bf2:dd4:20c1/64
    - fe80::9707:fb1f:65a3:84ab/64
    gateway: fe80::e228:6dff:fe88:bdf2
    method: auto
    nameservers:
    - fd00::e228:6dff:fe88:bdf2
    ready: true
  primary: true
  type: ethernet
  vlan: null
  wifi: null
supervisor_internet: true
```
