### ISSUE TITLE
updating to HAOS 11 Rc1 - network sensors become unknown eth0 to end0?

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/operating-system#2795]
### Describe the issue you are experiencing

Hi!

Just updated to HAOS 11RC1 (RPi4-4GB) and I noticed my network sensors from system monitor setup become unknown.

```
#System Health Sensors
- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: disk_free
    - type: disk_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: swap_use_percent
    - type: memory_free
    - type: processor_use
    - type: processor_temperature
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot
```

I see that "eth0" is not shown in my network properties anymore, but rather its now "end0"

Do I simply need to change it to end0 now?

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

HAOS 11.rc1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. update to HAOS 11.rc1
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no logs
```

### Anything in the Host logs that might be useful for us?

```txt
no logs
```
