### ISSUE TITLE
Update From 11.1 to 11.2 does not boot from correct slot

### ISSUE THREAD

**Issue by jscongdon** [home-assistant/operating-system#2983]
### Describe the issue you are experiencing

I am running Home Assistant on a Dell Laptop. No issues; it runs well.
I attempted to upgrade from 11.1 to 11.2 5 times, and it never appeared to work... then I had a thought to switch the slot manually. On a fresh boot, the machine will boot to SlotA = 11.1, so I forced it to boot to SlotB, and after full boot I see 11.2 is installed on it. It works great, with no issues. Then we lost power and the battery died... and on next boot, it defaults to SlotA again and I'm back to 11.1
The mechanism is in place to change the Slot it boots from is not working correctly.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

11.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgrade the OS
2. Watch it not boot the alternate slot

### Anything in the Supervisor logs that might be useful for us?

```txt
Not that I know of.
```

### Anything in the Host logs that might be useful for us?

```txt
Not that I know of.
```

**Comment by Yarr0tten** [comment]
Hi, i have exactly the same issue. My HA is also running on Dell laptop.

**Comment by jscongdon** [comment]
I haven't put much effort in, but a good "band-aid" would be if I could manually edit the boot process that selects the slot to boot from.

**Comment by FrankGiesecke** [comment]
I have the same issue running HAOS on a raspberry pi 4.

```shell
[core-ssh ~]$ ha os update --version "11.2"
Processing... Done.

Command completed successfully.
```

But after rebooting, the system ist still running version 11.1

```shell
[core-ssh ~]$ ha os info
board: rpi4-64
boot: A
data_disk: INTENSO-AA000000000000008831
update_available: true
version: "11.1"
version_latest: "11.2"
```

How can i force using slot 2?

**Comment by FrankGiesecke** [comment]
Some additional information:

I'm running two instances of HA. Both on Raspberry Pi 4 (rpi4-64) with SONOFF Zigbee Dongle and an USB SSD Drive.

Instance KG:
- SONOFF Zigbee 3.0 USB Dongle Plus V2
  ```yaml
  DEVLINKS: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220810183616-if00
    /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0
  DEVNAME: /dev/ttyACM0
  DEVPATH: >-
    /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0
  ID_BUS: usb
  ID_MODEL: SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2
  ID_MODEL_ENC: SONOFF\x20Zigbee\x203.0\x20USB\x20Dongle\x20Plus\x20V2
  ID_MODEL_ID: 55d4
  ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0
  ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_3_1_0
  ID_REVISION: '0442'
  ID_SERIAL: ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220810183616
  ID_SERIAL_SHORT: '20220810183616'
  ID_TYPE: generic
  ID_USB_DRIVER: cdc_acm
  ID_USB_INTERFACES: ':020201:0a0000:'
  ID_USB_INTERFACE_NUM: '00'
  ID_USB_MODEL: SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2
  ID_USB_MODEL_ENC: SONOFF\x20Zigbee\x203.0\x20USB\x20Dongle\x20Plus\x20V2
  ID_USB_MODEL_ID: 55d4
  ID_USB_REVISION: '0442'
  ID_USB_SERIAL: ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220810183616
  ID_USB_SERIAL_SHORT: '20220810183616'
  ID_USB_TYPE: generic
  ID_USB_VENDOR: ITEAD
  ID_USB_VENDOR_ENC: ITEAD
  ID_USB_VENDOR_ID: 1a86
  ID_VENDOR: ITEAD
  ID_VENDOR_ENC: ITEAD
  ID_VENDOR_ID: 1a86
  MAJOR: '166'
  MINOR: '0'
  SUBSYSTEM: tty
  TAGS: ':systemd:'
  USEC_INITIALIZED: '5309089'
  ```
- Intenso Portable SSD
  ```yaml
  DEVLINKS: >-
    /dev/disk/by-diskseq/28
    /dev/disk/by-id/usb-Intenso_Portable_SSD_20220812006D2-0:0
    /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0
  DEVNAME: /dev/sda
  DEVPATH: >-
    /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2- 2:1.0/host0/target0:0:0/0:0:0:0/block/sda
  DEVTYPE: disk
  DISKSEQ: '28'
  ID_BUS: usb
  ID_INSTANCE: '0:0'
  ID_MODEL: Portable_SSD
  ID_MODEL_ENC: Portable\x20SSD\x20\x20\x20\x20
  ID_MODEL_ID: '0579'
  ID_PART_TABLE_TYPE: gpt
  ID_PART_TABLE_UUID: 63cb89d4-5a0a-47bd-8e0f-c07cb289d1f1
  ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0
  ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_2_1_0-scsi-0_0_0_0
  ID_REVISION: '0506'
  ID_SERIAL: Intenso_Portable_SSD_20220812006D2-0:0
  ID_SERIAL_SHORT: 20220812006D2
  ID_TYPE: disk
  ID_USB_DRIVER: usb-storage
  ID_USB_INSTANCE: '0:0'
  ID_USB_INTERFACES: ':080650:080662:'
  ID_USB_INTERFACE_NUM: '00'
  ID_USB_MODEL: Portable_SSD
  ID_USB_MODEL_ENC: Portable\x20SSD\x20\x20\x20\x20
  ID_USB_MODEL_ID: '0579'
  ID_USB_REVISION: '0506'
  ID_USB_SERIAL: Intenso_Portable_SSD_20220812006D2-0:0
  ID_USB_SERIAL_SHORT: 20220812006D2
  ID_USB_TYPE: disk
  ID_USB_VENDOR: Intenso
  ID_USB_VENDOR_ENC: Intenso\x20
  ID_USB_VENDOR_ID: 152d
  ID_VENDOR: Intenso
  ID_VENDOR_ENC: Intenso\x20
  ID_VENDOR_ID: 152d
  MAJOR: '8'
  MINOR: '0'
  SUBSYSTEM: block
  TAGS: ':systemd:'
  USEC_INITIALIZED: '4621604'
  ```

Instance OG:
- SONOFF Zigbee 3.0 USB Dongle Plus
  ```yaml
  DEVLINKS: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e45352970013ec11b90623c7bd930c07-if00-port0
    /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-port0
  DEVNAME: /dev/ttyUSB0
  DEVPATH: >-
    /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/ttyUSB0/tty/ttyUSB0
  ID_BUS: usb
  ID_MODEL: Sonoff_Zigbee_3.0_USB_Dongle_Plus
  ID_MODEL_ENC: Sonoff\x20Zigbee\x203.0\x20USB\x20Dongle\x20Plus
  ID_MODEL_ID: ea60
  ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0
  ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_3_1_0
  ID_REVISION: '0100'
  ID_SERIAL: ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e45352970013ec11b90623c7bd930c07
  ID_SERIAL_SHORT: e45352970013ec11b90623c7bd930c07
  ID_TYPE: generic
  ID_USB_DRIVER: cp210x
  ID_USB_INTERFACES: ':ff0000:'
  ID_USB_INTERFACE_NUM: '00'
  ID_USB_MODEL: Sonoff_Zigbee_3.0_USB_Dongle_Plus
  ID_USB_MODEL_ENC: Sonoff\x20Zigbee\x203.0\x20USB\x20Dongle\x20Plus
  ID_USB_MODEL_ID: ea60
  ID_USB_REVISION: '0100'
  ID_USB_SERIAL: ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e45352970013ec11b90623c7bd930c07
  ID_USB_SERIAL_SHORT: e45352970013ec11b90623c7bd930c07
  ID_USB_TYPE: generic
  ID_USB_VENDOR: ITead
  ID_USB_VENDOR_ENC: ITead
  ID_USB_VENDOR_ID: 10c4
  ID_VENDOR: ITead
  ID_VENDOR_ENC: ITead
  ID_VENDOR_ID: 10c4
  MAJOR: '188'
  MINOR: '0'
  SUBSYSTEM: tty
  TAGS: ':systemd:'
  USEC_INITIALIZED: '4251439'
  ```
- Intenso Portable SSD
  ```yaml
  DEVLINKS: >-
    /dev/disk/by-diskseq/29 /dev/disk/by-id/ata-INTENSO_AA000000000000008831
    /dev/disk/by-id/usb-Intenso_Portable_SSD_DD564198851F0-0:0
    /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0
  DEVNAME: /dev/sda
  DEVPATH: >-
    /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host0/target0:0:0/0:0:0:0/block/sda
  DEVTYPE: disk
  DISKSEQ: '29'
  ID_ATA: '1'
  ID_ATA_DOWNLOAD_MICROCODE: '1'
  ID_ATA_FEATURE_SET_APM: '1'
  ID_ATA_FEATURE_SET_APM_CURRENT_VALUE: '128'
  ID_ATA_FEATURE_SET_APM_ENABLED: '1'
  ID_ATA_FEATURE_SET_HPA: '1'
  ID_ATA_FEATURE_SET_HPA_ENABLED: '1'
  ID_ATA_FEATURE_SET_PM: '1'
  ID_ATA_FEATURE_SET_PM_ENABLED: '1'
  ID_ATA_FEATURE_SET_SECURITY: '1'
  ID_ATA_FEATURE_SET_SECURITY_ENABLED: '0'
  ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN: '2'
  ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN: '2'
  ID_ATA_FEATURE_SET_SMART: '1'
  ID_ATA_FEATURE_SET_SMART_ENABLED: '1'
  ID_ATA_ROTATION_RATE_RPM: '0'
  ID_ATA_SATA: '1'
  ID_ATA_SATA_SIGNAL_RATE_GEN1: '1'
  ID_ATA_SATA_SIGNAL_RATE_GEN2: '1'
  ID_ATA_WRITE_CACHE: '1'
  ID_ATA_WRITE_CACHE_ENABLED: '1'
  ID_BUS: ata
  ID_MODEL: INTENSO
  ID_MODEL_ENC: >-
    INTENSO\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
  ID_PART_TABLE_TYPE: gpt
  ID_PART_TABLE_UUID: 63cb89d4-5a0a-47bd-8e0f-c07cb289d1f1
  ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0
  ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_2_1_0-scsi-0_0_0_0
  ID_REVISION: U0312A0
  ID_SERIAL: INTENSO_AA000000000000008831
  ID_SERIAL_SHORT: AA000000000000008831
  ID_TYPE: disk
  ID_USB_DRIVER: usb-storage
  ID_USB_INSTANCE: '0:0'
  ID_USB_INTERFACES: ':080650:080662:'
  ID_USB_INTERFACE_NUM: '00'
  ID_USB_MODEL: Portable_SSD
  ID_USB_MODEL_ENC: Portable\x20SSD\x20\x20\x20\x20
  ID_USB_MODEL_ID: '0578'
  ID_USB_REVISION: '0214'
  ID_USB_SERIAL: Intenso_Portable_SSD_DD564198851F0-0:0
  ID_USB_SERIAL_SHORT: DD564198851F0
  ID_USB_TYPE: disk
  ID_USB_VENDOR: Intenso
  ID_USB_VENDOR_ENC: Intenso\x20
  ID_USB_VENDOR_ID: 152d
  MAJOR: '8'
  MINOR: '0'
  SUBSYSTEM: block
  TAGS: ':systemd:'
  USEC_INITIALIZED: '4128996'
  ```

Instance KG can be updated without any issues and is now running version 11.2

Instance OG can be updated but is still running version 11.1

Please, can some one explain why?

**Comment by jscongdon** [comment]
It is odd that you are not seeing the same issue on two environments with the same hardware.
I believe the PC-based installations issue deals with systems with a BIOS boot instead of UEFI. If you are able to connect a display and keyboard to the Pi that is not booting correctly, you can try to interrupt the boot process at the time it displays the "boot menu". You will be able to manually select the alternate slot. After booting that slot, check the version.

**Comment by FrankGiesecke** [comment]
@jscongdon Unfortunately ist it not possible to attach a monitor to the Pi :(

Both Pi's are setup simultaneous. I have made no changes to the startup process.

**Comment by FrankGiesecke** [comment]
After posting my device information I realized, that there is a difference between the two systems and their USB SSD recognation.

On instance KG, the USB SSD is listed as:
```yaml
DEVTYPE: disk
DISKSEQ: '28'
ID_BUS: usb
ID_INSTANCE: '0:0'
ID_MODEL: Portable_SSD
ID_MODEL_ENC: ...
ID_PART_TABLE_TYPE: gpt
``` 

On instance OG, the USB SSD is listed as:
```yaml
DEVTYPE: disk
DISKSEQ: '29'
ID_ATA: '1'
ID_ATA_* ...
ID_BUS: ata
ID_MODEL: INTENSO
ID_MODEL_ENC: ...
ID_PART_TABLE_TYPE: gpt
```
