### ISSUE TITLE
Docker issue: outbound IPv6 not working

### ISSUE THREAD

**Issue by Giga-Pudding** [home-assistant/operating-system#3019]
**Inbound** IPv6 connections work, **outbound** IPv6 connections do not work.
For example: running shell commands which depend on IPv6:

Ping IPv4:
```
[core-ssh ~]$ ping google.com
PING google.com (142.250.185.110): 56 data bytes
64 bytes from 142.250.185.110: seq=0 ttl=118 time=17.191 ms
64 bytes from 142.250.185.110: seq=1 ttl=118 time=17.026 ms
64 bytes from 142.250.185.110: seq=2 ttl=118 time=17.682 ms
```
Ping IPv6:
```
[core-ssh ~]$ ping6 google.com
PING google.com (2a00:1450:4001:80f::200e): 56 data bytes
ping6: sendto: Address not available
```
Curl IPv4:
```
[core-ssh ~]$ curl -4 https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```
Curl IPv6:
```
[core-ssh ~]$ curl -6 https://google.com
curl: (7) Failed to connect to google.com port 443 after 18 ms: Couldn't connect to server
```

My HA OS setup has a working IPv6 config and i successfully tested inbound IPv6 connections.

```
[core-ssh ~]$ ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: true
interfaces:
- connected: true
  enabled: true
  interface: enp0s18
  ipv4:
    address:
    - 10.40.4.111/24
    gateway: 10.40.4.1
    method: static
    nameservers:
    - 10.40.4.1
    ready: true
  ipv6:
    address:
    - 2003:f2:xxxx:xxxx:xxxx:xxxx:4535:927d/64
    - fe80::3cff:xxxx:xxxx:6795/64
    gateway: fe80::2a0:xxxx:xxxx:937b
    method: auto
    nameservers: []
    ready: true
  mac: DE:xx:xx:xx:xx:EB
  primary: true
  type: ethernet
  vlan: null
  wifi: null
supervisor_internet: true
```

I checked `/etc/docker/daemon.json` on the HA OS host and found:

```
{
  "experimental": true,
  "ip6tables": true
}
```
So my understanding is, that IPv6 should work, but doesn't. The core container cannot establish outbound IPv6 connections. By enabling SSH access to the host (port 22222) a was able to verify, that the host can communicate outbound via IPv6 fine. So this is a docker / container issue.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

11.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Login to the core container and run some shell commands to compare:
`curl -4 https://google.com`
`curl -6 https://google.com`
`ping google.com`
`ping6 google.com`
