### ISSUE TITLE
Update to 12.3 prevents boot on Fujitsu Esprimo Q920

### ISSUE THREAD

**Issue by asciinaut** [home-assistant/operating-system#3348]
### Describe the issue you are experiencing

Updated Home Assistant OS from 12.2 to 12.3.

After reboot system doesn't boot properly

Sometimes it boots into rescue mode automatically if no option is chosen manually after reboot. Sometimes it shows:

```
Booting "Slot B (recue shell)"

Trying to terminate EFI services again
error: couldn't retrieve memory map.

Failed to boot both default and fallback entries.
```

Choosing the slots manually neither of the slots (Slot A, Slot B nor the respective rescue slots) boot. 

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

inaccessible

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Start the announced update from 12.2 to 12.3 in the Webinterface
2. wait for the reboot

### Anything in the Supervisor logs that might be useful for us?

```txt
inaccessible
```

### Anything in the Host logs that might be useful for us?

```txt
inaccessible
```

### System information

inaccessible

**Comment by asciinaut** [comment]
probably related to #3347 ?

**Comment by agners** [comment]
> probably related to #3347 ?

Unlikely, as this is Home Assistant Yellow.

This is probably related to the GRUB revert in #3324.

What x86-64 machine are you running on?

> Sometimes it boots into rescue mode automatically

What rescue mode exactly? Is `ha os info` working in that shell?

Probably your best way forward here is to replace the GRUB bootloader on the first partition of your boot disk (e.g. using a Ubuntu Live USB flash drive). You can find older version of the GRUB bootloader capable of booting HAOS in this comment https://github.com/home-assistant/operating-system/issues/3305#issuecomment-2055918375.

**Comment by asciinaut** [comment]
Thank you very much for your answer.

> What x86-64 machine are you running on?

Fujitsu Esprimo Q920 - Intel Core i5 4590T

> What rescue mode exactly? Is ha os info working in that shell?

This does not work in the rescue shell but I can exit the rescue shell which makes the supervisor start. In that case it is HAOS 12.2 so I assume I starts from Slot B rescue. From that poin on I have access to the system and can provide additional information.

```
➜  ~ ha os info
board: generic-x86-64
boot: B
boot_slots:
  A:
    state: inactive
    status: bad
    version: "12.3"
  B:
    state: booted
    status: good
    version: "12.2"
data_disk: MicroFrom-256GB-SATA3-SSD-07042223E0108
update_available: true
version: "12.2"
version_latest: "12.3"
```

Start into this rescue mode is successfull in about 1 out of 10 boot attempts. Otherwise I only see the mentioned error.
