### ISSUE TITLE
State of a helper sensor returns `Unavailable` when you edit the code to change the state value

### ISSUE THREAD

**Issue by MrCaspan** [home-assistant/operating-system#3823]
### Describe the issue you are experiencing

I created a helper that returns the current tariff for my hydro company based on their rules

sensor.hydro_current_tariff
```
{% set date = now() %}
{% set isHoliday = is_state('calendar.canada_on', 'on') %}
{% set isWeekend = date.isoweekday() in [6,7] %}
{% set isSummer  = date.month in [5,6,7,8,9,10] %}

{% if isWeekend or isHoliday %}
  {% set lookup = 'OOOOOOOOOOOOOOOOOOOOOOOO' %}
{% elif isSummer %}
  {% set lookup = 'OOOOOOOMMMMPPPPPPMMOOOOO' %}
{% else %}
  {% set lookup = 'OOOOOOOPPPPMMMMMMPPOOOOO' %}
{% endif %}
{% set map = {'O': 'Off-Peak', 'M': 'Mid-Peak', 'P': 'On-Peak'} %}
{{ map[lookup[now().hour]] }}
```

It will return only "Off-Peak | Mid-Peak | On-Peak" based on the time of day and year. This code works and is solid for a month.

I created 10 Utility Meters with the same tariffs Off-Peak | Mid-Peak | On-Peak  each utility meter is tracing an entity's energy usage 

I gave each UM a label ID of utility_meter_tou

I created an automation that triggers on the change of state, set the tariff of all the utility meters to the state it changed to

**Automation YAML**
```
alias: Hydro - TOU Change
description: >-
  When the helper for TOU changes to a new value, update the parent utility
  meter to the new TOU tariff
triggers:
  - trigger: state
    entity_id:
      - sensor.hydro_current_tariff
    to: null
conditions: []
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: "{{ trigger.to_state.state }}"
    target:
      label_id: utility_meter_tou
    alias: Update All Utility Meters to New TOU
mode: single
```

The problem I was having is that I was using the UI to editing my template code in the helper to change the output of the sensor to something different to for testing and triggering the automation. Every time I did this {{ trigger.to_state.state }} evaluated to unavailable. When I changed the state using the Developer Tools > States it worked as expected and {{ trigger.to_state.state }} evaluated to the state that I change it to!

I am not sure if there is a race condition when using the UI to edit the template code and therefor it becomes unavailable, but I don't believe this is the expected outcome..

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

core-2025.1.3

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

This is a VM on TrueNAS

### Steps to reproduce the issue

Steps are in the initial statement

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

### Additional information

**Automation trace Logs**

Update All Utility Meters to New TOU
Executed: January 23, 2025 at 2:01:22 PM
Error: Option unavailable is not valid for entity select.dryer_utility_meter, valid options are: On-Peak, Off-Peak, Mid-Peak
Result:
params:
  domain: select
  service: select_option
  service_data:
    option: unavailable
    label_id:
      - utility_meter_tou
  target:
    label_id:
      - utility_meter_tou
running_script: false

**Step Config**
action: select.select_option
metadata: {}
data:
  option: '{{ trigger.to_state.state }}'
target:
  label_id: utility_meter_tou
alias: Update All Utility Meters to New TOU
