### ISSUE TITLE
System not start

### ISSUE THREAD

**Issue by kaidem4** [home-assistant/operating-system#3838]
### Describe the issue you are experiencing

After update to last version, the system dont start anymore. black screen and not keyboard abailable. Only ping responses.
rpi 5 8Gb

### What operating system image do you use?

rpi5-64  (Raspberry Pi 5 64-bit OS)

### What version of Home Assistant Operating System is installed?

14.0

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

rpi5

### Steps to reproduce the issue

1.automatic from ha web
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
i cant access the system to view
```

### Anything in the Host logs that might be useful for us?

```txt
The sistem not start. I cant view anything
```

**Comment by bigskookum** [comment]
I also got this, upgrading to 14.2 from 14.1 on x86. I managed to boot back into 14.1 using this procedure:

https://github.com/home-assistant/operating-system/issues/2272#issuecomment-1600300443

The  /dev/sda8 partition was named haaos-data-dis

**Comment by idcrook** [comment]
Doing HAOS 14.2 Update from 14.1 I also got an unresponsive system.  rpi5-64 as well.

**Comment by idcrook** [comment]
HAOS seems to know it was "bad"

> _Update_: When plugged back in power to troubleshoot, the system booted into HAOS **14.1** -- and Settings update was offering **14.2** Update again.
> 
> FWIW, rpi5 4GB HAOS on m.2 NVMe SSD

```
ha > os info 
board: rpi5-64
boot: A
boot_slots:
  A:
state: booted status: good version: "14.1"
  B:
state: inactive
status: bad 
version: "14.2"
data_disk: INTEL-SSDPEKNUO10TZ-PHKA12630BBY1P0B
update_available: true 
version: "14.1"
version_latest: "14.2"
```
