### ISSUE TITLE
Raspberry Pi 3 32-bit fails to boot Home Assistant OS 15.0

### ISSUE THREAD

**Issue by thebigmacburger** [home-assistant/operating-system#3965]
### Describe the issue you are experiencing

14.2 works, but 15.0 fails to start, whether installed fresh or by an upgrade.

Connecting a display by HDMI reveals that U-Boot is waiting on an Ethernet connection, and upon receiving a connection, the system attempts to boot via PXE (which is interesting because my OpenWRT router does not have TFTP enabled).

After the PXE boot fails, the system eventually drops to the U-Boot command line.

### What operating system image do you use?

rpi3 (Raspberry Pi 3 32-bit OS)

### What version of Home Assistant Operating System is installed?

15.0

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

Raspberry Pi 3 Model B
Ethernet
Router with OpenWRT 23.05

### Steps to reproduce the issue

1. Write the image to the SD card
2. Insert the SD card and power the Raspberry Pi on
3. Observe the system try to boot via PXE

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

**Comment by dersch81** [comment]
Same issue here. It was running with my RPi3 B+ on 14.2 but fails booting after upgrading to 15.0. It tries to boot via PXE, stops at HAOS CLI but does not react to any keyboard connected. 

Seems 15.0 breaks all the RPI and other microboards. Is it an untested release?

**Comment by berkoffff** [comment]
Same here. RPI 3b+, trying pxe boot, lan card off.

**Comment by sairon** [comment]
Strange, the PXE boot happens because U-Boot fails to load the kernel. Maybe it's an SD card issue? Both on RPi 3B and 3B+ 15.0 is running fine for me:
```
# ha os info
board: rpi3-64
boot: B
boot_slots:
  A:
    state: inactive
    status: good
    version: 15.1.dev20250320
  B:
    state: booted
    status: good
    version: "15.0"
data_disk: SD64G-0x40500c12
update_available: true
version: "15.0"
version_latest: 15.1.dev20250320
```

Also I believe there would be more reports at this time if it were a generic issue.
